### ISSUE TITLE
UI freezing on linux-arm 

### ISSUE THREAD

**Issue by Naim-h** [AvaloniaUI/oxyplot-avalonia#10]
I have Avalonia project and try to run chart with oxyplot-avalonia on it,it works well on windows but when I publish it to run on linux-arm (I used ARM Cortex-A9 embedded device), the page which I use chart on it become freeze(without any exception on the output).
as I know it freezes when it try to render the chart, because if I don't pass DataPoint to it , the page works as usual.

**Comment by VisualMelon** [comment]
Does e.g. the example browser work on the same device? I can't test on ARM, so I probably can't help, but can you run it under a debugger and work out where it is freezing? (e.g. is it stuck in a tight loop, does it seem to be deadlocking, etc.)

**Comment by Naim-h** [comment]
Thanks for your reply.
I try to attach project to visual studio debugger but I can't find any crash on the code.
Also I change the project avalonia version to 0.9.4 and after that I do some modification to fix some build error on it, (fore example PlotBase.cs line 342 and 343 , I replace _tracker_ with _tracker.Control_ also replace _using Portable.Xaml.Markup;_ with  _using Avalonia.Markup.Xaml_ ) do you think these changes cause of the problem?

**Comment by VisualMelon** [comment]
Are you able to pause the debugger while it is frozen and upload the callstacks?

**Comment by Naim-h** [comment]
I try to get the callstacks but when I pause the debugger after set the _PlotView_ Model, the callstack is empty.
I try to run the SimpleDemo project on linux device, and I found out if I run it with avalonia 0.8.0 it works well , but when I upgrade the avalonia version to 0.9.4 or 0.9.11 , it doesn't display the chart and UI become frozen.

**Comment by VisualMelon** [comment]
That might suggest something is silently crashing within Avalonia then. Would you be able to upload the two versions, one which works and one which doesn't? I presume the difference is just the csproj, in which case just uploading those as a gist would be great.

I'm afraid without an ARM device, I'm unlikely to get anywhere, but if you or someone else can debug it, it may be possible to step through the rendering routines to find where it goes wrong. That said, we should probably check if the same happens on x64 linux.

**Comment by Naim-h** [comment]
in the attachment you can find the demo version which is not working(use avalonia 0.9.4).
also I did some small modification on _OxyPlot.Avalonia_ project and adapt it with avalonia 0.9.4.
please take a look on it too.
the sample in the git (https://github.com/AvaloniaUI/oxyplot-avalonia/tree/master/Source/Examples/Avalonia/SimpleDemo) use avalonia 0.8.0 and it works well on the ARM linux.

[Source.zip](https://github.com/AvaloniaUI/oxyplot-avalonia/files/4925462/Source.zip)

**Comment by Naim-h** [comment]
I test it in x64 linux virtual machine and it works. so it's crash only on ARM device

**Comment by VisualMelon** [comment]
Could you try the 0.1 port in https://github.com/oxyplot/oxyplot-avalonia/pull/23 ? (e.g. just check the example browser works)

**Comment by Naim-h** [comment]
Did you merge the changes on the master  ? I can't find the changes there and also there is no any other branches .

**Comment by VisualMelon** [comment]
No, but I've tested the jp2masa's branch, and it looks fine. I'm just wondering if maybe this is an Avalonia issue that may have been fixed but didn't appear in the 0.9 branch.

**Comment by Naim-h** [comment]
I try to run it but now I got this error,
`root@colibri-imx6:/home/Wittmann/Installed/Oxyplot# ./ExampleBrowser
Unhandled exception. System.InvalidOperationException: Default font family name can't be null or empty.
   at Avalonia.Media.FontManager..ctor(IFontManagerImpl platformImpl)
   at Avalonia.Media.FontManager.get_Current()
   at Avalonia.Rendering.RendererBase..ctor(Boolean useManualFpsCounting)
   at Avalonia.Rendering.DeferredRenderer..ctor(IRenderRoot root, IRenderLoop renderLoop, ISceneBuilder sceneBuilder, IDispatcher dispatcher, IDeferredRendererLock rendererLock)
   at Avalonia.X11.X11Window.CreateRenderer(IRenderRoot root)
   at Avalonia.Controls.TopLevel..ctor(ITopLevelImpl impl, IAvaloniaDependencyResolver dependencyResolver)
   at Avalonia.Controls.WindowBase..ctor(IWindowBaseImpl impl, IAvaloniaDependencyResolver dependencyResolver)
   at Avalonia.Controls.WindowBase..ctor(IWindowBaseImpl impl)
   at Avalonia.Controls.Window..ctor(IWindowImpl impl)
   at Avalonia.Controls.Window..ctor()
   at ExampleBrowser.MainWindow..ctor() in D:\Samples\Oxyplot\oxyAvalonia git\oxyplot-avalonia\Source\Examples\Avalonia\ExampleBrowser\MainWindow.xaml.cs:line 9
   at ExampleBrowser.App.OnFrameworkInitializationCompleted() in D:\Samples\Oxyplot\oxyAvalonia git\oxyplot-avalonia\Source\Examples\Avalonia\ExampleBrowser\App.xaml.cs:line 18
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at ExampleBrowser.Program.Main(String[] args) in D:\Samples\Oxyplot\oxyAvalonia git\oxyplot-avalonia\Source\Examples\Avalonia\ExampleBrowser\Program.cs:line 10
`

I try to set a _DefaultFont_ on _PlotModel_  but the result is same.

**Comment by rstm-sf** [comment]
Let's still have a discussion in the main project) https://github.com/oxyplot/oxyplot-avalonia/issues/21

**Comment by Gillibald** [comment]
`Default font family name can't be null or empty.` means Skia's FontManger is dysfunctional. Probably missing FontConfig.

**Comment by Naim-h** [comment]
@Gillibald Thanks for your comment, I try to set the default font on MainWindow constructor, but the Avalonia.Media.FontManager .Current.DefaultFontFamilyName; doesn't change, it use **_Segoe UI_** as a default font and I don't have this font on my ARM linux machine, 
Could you please guide me how can I set the DefaultFont on avalonia ?

**Comment by Naim-h** [comment]
Finally I fixed it.
Oxyplot.core use **_Segoe UI_** font as default font in the source code, so when I try to run it on the Arm linux machine which it hasn't _**Segoe UI**_ by default , the application crashed. 
I changed the default point when initialized the _PlotModel_ and now it works well.
Thanks for your support

**Comment by Gillibald** [comment]
The issue is still there. Somehow FontConfig isn't working for you so you don't get any font matches. The only way to get this working is to specify a font that is present on the system.

**Comment by VisualMelon** [comment]
@Gillibald is there any issue on the OxyPlot/OxyPlot-Avalonia side of things in your assessment, or a way we can detect the issue and avoid hanging?

**Comment by Gillibald** [comment]
You get this warning when the font manager isn't working properly:

> `Default font family name can't be null or empty.` means Skia's FontManger is dysfunctional. Probably missing FontConfig.

In general you either embed a default font or you let Avalonia look up the default. That happens when you don't specify a FontFamily.

**Comment by VisualMelon** [comment]
Ah, yeah, seems obvious now. I think our Skia renderer does something similar. I'll have a look into making it less fragile over the weekend.

**Comment by Naim-h** [comment]
@Gillibald as I found out there is 2 different issue , I solved the issue for avalonia 0.9.4 verion by setting the oxyplot default font at initialize time.
but I still  get the _Default font family name can't be null or empty._ error on avalonia 0.10.0-preview1. I guess the new features of avalonia (Avalonia.Media.FontManager..ctor(IFontManagerImpl platformImpl)) is not working on the Arm linux machine.

**Comment by Gillibald** [comment]
Avalonia `0.9.4` has the same issue it just doesn't throw an exception. You are still not able to use font matching because FontConfig isn't working properly.
